apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat9
  template:
    metadata:
      labels:
        app: tomcat9
    spec:
      containers:
      - name: tomcat9
        image: veeru1449/tomcat:v28
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat9
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: tomcat-route
spec:
  to:
    kind: Service
    name: tomcat-service
  port:
    targetPort: 8080
  tls:
    termination: edge
  wildcardPolicy: None

